export type AppSettingKey =
  | "TRM_COP"
  | "SMS_PRICE_PER_MESSAGE"
  | "SMS_PRICE_PER_MESSAGE_TWILIO"
  | "SMS_PRICE_PER_MESSAGE_MASIVAPP"
  | "EMAIL_PRICE_PER_MESSAGE"
  | "SMS_CAMPAIGN_PRICE_PER_MESSAGE"
  | "SMS_CAMPAIGN_PRICE_PER_MESSAGE_TWILIO"
  | "SMS_CAMPAIGN_PRICE_PER_MESSAGE_MASIVAPP"
  | "EMAIL_CAMPAIGN_PRICE_PER_MESSAGE"
  | "SMS_PRICE_PER_MESSAGE_COP"
  | "SMS_PRICE_PER_MESSAGE_TWILIO_COP"
  | "SMS_PRICE_PER_MESSAGE_MASIVAPP_COP"
  | "EMAIL_PRICE_PER_MESSAGE_COP"
  | "SMS_CAMPAIGN_PRICE_PER_MESSAGE_COP"
  | "SMS_CAMPAIGN_PRICE_PER_MESSAGE_TWILIO_COP"
  | "SMS_CAMPAIGN_PRICE_PER_MESSAGE_MASIVAPP_COP"
  | "EMAIL_CAMPAIGN_PRICE_PER_MESSAGE_COP";

export type AppSettingType = "STRING" | "NUMBER" | "BOOLEAN";

export interface AppSetting {
  _id?: string;
  key: AppSettingKey;
  value: string | number | boolean;
  type: AppSettingType;
  source?: "ENV" | "DB" | string;
  createdAt?: Date;
  updatedAt?: Date;
}
